server:
  port: 12001
  
  
spring:
    
    #mongo配置
    data:
      mongodb:
        database: user_data
        uri: mongodb://gangtise:PrTLMM2BSpHJVJ91CrWc46tTBnuWI3hHjKEyYO3SaHzux3Rt8JCTJBj6DwnfoiNQrhJLAuGWH1uJHmZ3Pz1zbQ==@gangtise.documents.azure.cn:10255/?ssl=true&replicaSet=globaldb
