server:
  port: 12001

spring:              
    #mongo配置
  data:
    mongodb:
      #database: user_data
      uri: mongodb://gangtise:abcd1234@40.73.110.216:27017/user_data

task:
  usersector:    
    remainNum: 10
  userquota:
    remainNum: 10
  userbrowser:
    #1:按保留条数 2：按保留天数
    flag: 1
    remain: 100
        
