server:
  port: 10010
  
spring:
  redis:
    host: gangtise.redis.cache.chinacloudapi.cn
    port: 6379
    password: tAYgnsr3MSE8onaB3M083c91ZyVOPI5tvE1Ze98e11E=

ignore:
  urls:
    - /**/*.css
    - /oauth/**
    - /auth/oauth/**
    - /actuator/**
    - /hystrix/**
    - /swagger-resource/**
    - /swagger-ui.html/**
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs 
    - /rscLogin
    - /captcha.jpg